name: Actions DEV

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Crear entorno virtual
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
      - name: Activar entorno virtual
        run: |
          if[ -f venv/bin/activate ]; then source venv/bin/activate; fi
      - name: Instalar dependencias
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Unit Testing with pytest
        run: |
          pytest